### ISSUE TITLE
Can this module be merged with the 2 other layouts modules and/or localgov_base?

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_extra_layouts#1]
Hi @justinepocock 

Do you think we need to keep this as a separate module, or should we merge it with the functionality of

- https://github.com/localgovdrupal/localgov_paragraphs/tree/2.x/modules/localgov_paragraphs_layout
- https://github.com/localgovdrupal/localgov_subsites/blob/2.x/localgov_subsites.layouts.yml
- There's somewhere else that provides the layouts for the general layouts in subsites, but I'm not sure what repo they are in

**Comment by justinepocock** [comment]
Wasn't sure where best to put it so just renamed the module we have, I didn't spot localgov_paragraphs_layout actually. Happy to move it to there. localgov_subsites seems too particular.

**Comment by justinepocock** [comment]
https://github.com/localgovdrupal/localgov_paragraphs/pull/157 added 4 col here, I'll do the rest when I can find a bit more time.

**Comment by markconroy** [comment]
Localgov Paragraphs Layout is the module that gives us these cool options for the "Page Section" field. I don't think anyone knows about it, and it's not enabled by default. 
![Screenshot 2023-11-15 at 11 25 19](https://github.com/localgovdrupal/localgov_extra_layouts/assets/2183332/cc7686c3-390e-43b5-9095-b2c415f20c78)

**Comment by justinepocock** [comment]
Ah yes I found these when trying to get publications to do the same. Moved them into there.

**Comment by markconroy** [comment]
@justinepocock can you remember the status of this module? Have we moved all the layouts to localgov_paragraphs, or should we keep this module so there's extra layouts (that are optional if people want them)? And by extension can be used via layout builder and/or paragraphs?

**Comment by justinepocock** [comment]
Looks like I only moved the four column layout to the paragraphs layout module. The 33/66 two column version should probably be moved. Only notice one person ask for this in the past 10 months. 

https://github.com/localgovdrupal/localgov_paragraphs/pull/157

**Comment by markconroy** [comment]
Seems like this might be a niche module, as in only some councils might want those extra layouts and might be best not to make them available to all councils in case they use them "just because they can".

So, let's leave this as independent and we'll add it to packagist so people can add it to their sites. 

Does that sound like a reasonable approach?

**Comment by justinepocock** [comment]
That works for me, I've used this module on other projects so selfishly this makes it easier for me too :D

**Comment by andybroomfield** [comment]
Is layouts also compatible with layout builder? If so I would keep it a separate module and add it to packagist. This would avoid needing a dependency on paragraphs... that said if it's a Localgov drupal module paragraphs might already be there. If it was merged though I'd make it a sub module to avoid too many layouts for those that don't need it.
